# https://ci.appveyor.com/project/jkbrzt/httpie
build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python35"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
#  - "%PYTHON%/Scripts/pip.exe install -U pip setuptools"
  - "%PYTHON%/Scripts/pip.exe install -e ."

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/http.exe --debug"
  - "%PYTHON%/python.exe setup.py test"
