# https://ci.appveyor.com/project/jkbr/httpie
build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
init:
  - ps: "ls C:/Python*"
install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe c:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -e ."
test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/http.exe --debug"
  - "%PYTHON%/python.exe setup.py test"
