name: Build

on: [push]

jobs:

  extras:
    # Run coverage and extra tests only once
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install --upgrade pip
      - run: make install
      - run: make pycodestyle
      - run: make test
      - run: make codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_REPO_TOKEN }}
      - run: make test-dist

  test:
    # Run core HTTPie tests everywhere
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install --upgrade --editable .
      - run: python setup.py test
