name: Release on PyPI

on:
  # Add a "Trigger" button to manually start the workflow.
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to release from"
        required: true
        default: "master"
  # It could be fully automated by uncommenting following lines.
  # Let's see later if we are confident enough to try it :)
  # release:
  #   types:
  #     - published

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: PyPI configuration
        run: |
          echo "[distutils]\nindex-servers=\n    httpie\n\n[httpie]\nrepository = https://upload.pypi.org/legacy/\n" > $HOME/.pypirc
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: make publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
